#!/bin/sh /etc/rc.common

START=21


start() {
    echo "Starting pwm-fan"
    while true
    do
      if ! pgrep -f "pwm-fan.sh" > /dev/null
      then
        /usr/bin/pwm-fan.sh &
      fi
        sleep 60
    done &
}
