#!/bin/sh /etc/rc.common

START=99

start() {

    interface="eth0"
    for i in $(seq 1 10)
    do
        link_status=$(ethtool $interface | grep 'Link detected:' | cut -d ':' -f 2 | tr -d ' ')
        if [ "$link_status" = "yes" ]
        then
            echo "YT8531C load successful"
            break
        else
            echo "YT8531C loaded failed"
            echo "YT8531C will restart"
            ifconfig $interface down
            sleep 3
            ifconfig $interface up
            sleep 3
            ethtool -s eth0 autoneg on
            sleep 3
        fi
    
    done
    
}
